module.exports = {
    plugins: [require('daisyui')],
    daisyui: {
        themes: [
            {
                Sunset: {
                    primary: '#363234',
                    secondary: '#f2ece4',
                    accent: '#e7dccc',
                    neutral: '#5c3f5a',
                    'base-100': '#FFFFFF',
                    'base-200': '#eff0f7',
                },
            },
            'light',
            'dark',
            'cupcake',
            'bumblebee',
            'emerald',
            'corporate',
            'synthwave',
            'retro',
            'cyberpunk',
            'valentine',
            'halloween',
            'garden',
            'forest',
            'aqua',
            'lofi',
            'pastel',
            'fantasy',
            'wireframe',
            'black',
            'luxury',
            'dracula',
            'cmyk',
            'autumn',
            'business',
            'acid',
            'lemonade',
            'night',
            'coffee',
            'winter',
        ],
    },
};
