// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IconEpAim: typeof import('~icons/ep/aim')['default']
    IEpAddLocation: typeof import('~icons/ep/add-location')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpFlag: typeof import('~icons/ep/flag')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpShLocation: typeof import('~icons/ep/sh-location')['default']
    IEpShopLocation: typeof import('~icons/ep/shop-location')['default']
    IEpShoppingCard: typeof import('~icons/ep/shopping-card')['default']
    IEpShoppingCardFull: typeof import('~icons/ep/shopping-card-full')['default']
    IEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IEpShoppingCartFull: typeof import('~icons/ep/shopping-cart-full')['default']
    IEpShoppingLocation: typeof import('~icons/ep/shopping-location')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Message: typeof import('element-plus/es')['ElMessageDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
