// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpFlag: typeof import('~icons/ep/flag')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpOpportunity: typeof import('~icons/ep/opportunity')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpShoppingCart: typeof import('~icons/ep/shopping-cart')['default']
    IEpShoppingCartFull: typeof import('~icons/ep/shopping-cart-full')['default']
    IEpShoppingTrolley: typeof import('~icons/ep/shopping-trolley')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
