const interopDefault = r => r.default || r || [];
const styles = {
  "components/AppFooter.vue": () => import('./_nuxt/AppFooter-styles.7e4e9d70.mjs').then(interopDefault),
  "pages/pc/design/index.vue": () => import('./_nuxt/index-styles.8c8e3769.mjs').then(interopDefault),
  "pages/pc/draw/components/generateImage.vue": () => import('./_nuxt/generateImage-styles.8caecadc.mjs').then(interopDefault),
  "pages/pc/draw/index.vue": () => import('./_nuxt/index-styles.1503aafe.mjs').then(interopDefault),
  "pages/pc/home/index.vue": () => import('./_nuxt/index-styles.883d022a.mjs').then(interopDefault),
  "pages/pc/tags/chitu.vue": () => import('./_nuxt/chitu-styles.82c81fdb.mjs').then(interopDefault),
  "pages/pc/profile/index.vue": () => import('./_nuxt/index-styles.803cf40c.mjs').then(interopDefault),
  "../node_modules/nuxt-icon/dist/runtime/Icon.vue": () => import('./_nuxt/Icon-styles.1f0d30f3.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.3bed16f1.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.a99704c9.mjs').then(interopDefault),
  "pages/pc/login/index.vue": () => import('./_nuxt/index-styles.92c6435e.mjs').then(interopDefault),
  "pages/pc/tags/components/eHentai.vue": () => import('./_nuxt/eHentai-styles.80b2aa85.mjs').then(interopDefault),
  "pages/pc/tags/components/eHentaiMore.vue": () => import('./_nuxt/eHentaiMore-styles.53943cd5.mjs').then(interopDefault),
  "pages/pc/tags/eh.vue": () => import('./_nuxt/eh-styles.abc43c93.mjs').then(interopDefault),
  "layouts/default.vue": () => import('./_nuxt/default-styles.8f3dd99d.mjs').then(interopDefault),
  "pages/pc/tags/gelbooru.vue": () => import('./_nuxt/gelbooru-styles.322742bc.mjs').then(interopDefault),
  "pages/pc/tags/index.vue": () => import('./_nuxt/index-styles.786e0eab.mjs').then(interopDefault),
  "pages/pc/tags/components/gelbooru.vue": () => import('./_nuxt/gelbooru-styles.0cc023cd.mjs').then(interopDefault),
  "pages/pc/template/nsfw.vue": () => import('./_nuxt/nsfw-styles.f5a0ea4d.mjs').then(interopDefault),
  "pages/pc/utils/components/imageAnalysis.vue": () => import('./_nuxt/imageAnalysis-styles.e5dac609.mjs').then(interopDefault),
  "pages/pc/utils/index.vue": () => import('./_nuxt/index-styles.3647b035.mjs').then(interopDefault),
  "pages/pc/utils/components/promptBeautiful.vue": () => import('./_nuxt/promptBeautiful-styles.c60514c4.mjs').then(interopDefault),
  "pages/pc/template/sfw.vue": () => import('./_nuxt/sfw-styles.4e42becb.mjs').then(interopDefault),
  "direction/animate/index.ts": () => import('./_nuxt/index-styles.4790aad8.mjs').then(interopDefault),
  "components/pc/LinkList.vue": () => import('./_nuxt/LinkList-styles.9dd6b2ac.mjs').then(interopDefault),
  "components/AppHeader.vue": () => import('./_nuxt/AppHeader-styles.7bc82ade.mjs').then(interopDefault),
  "components/pc/TemplateDetail.vue": () => import('./_nuxt/TemplateDetail-styles.05b0e733.mjs').then(interopDefault),
  "components/pc/AreaTitle.vue": () => import('./_nuxt/AreaTitle-styles.883e00e8.mjs').then(interopDefault),
  "components/AppBanner.vue": () => import('./_nuxt/AppBanner-styles.fdb85597.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue": () => import('./_nuxt/welcome-styles.cc8732e9.mjs').then(interopDefault),
  "components/pc/ShopLayer.vue": () => import('./_nuxt/ShopLayer-styles.30bfb7a2.mjs').then(interopDefault),
  "components/common/WaterFall/index.vue": () => import('./_nuxt/index-styles.5368c765.mjs').then(interopDefault),
  "components/pc/FixMenu.vue": () => import('./_nuxt/FixMenu-styles.dacdceec.mjs').then(interopDefault),
  "components/pc/AnimationButton.vue": () => import('./_nuxt/AnimationButton-styles.98b5259e.mjs').then(interopDefault)
};

export { styles as default };
