// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    IEpArrowLeftBold: typeof import('~icons/ep/arrow-left-bold')['default']
    IEpCheck: typeof import('~icons/ep/check')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpCollectionTag: typeof import('~icons/ep/collection-tag')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDeleteFilled: typeof import('~icons/ep/delete-filled')['default']
    IEpDocumentCopy: typeof import('~icons/ep/document-copy')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFiles: typeof import('~icons/ep/files')['default']
    IEpFlag: typeof import('~icons/ep/flag')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpGuide: typeof import('~icons/ep/guide')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    IEpMore: typeof import('~icons/ep/more')['default']
    IEpOpportunity: typeof import('~icons/ep/opportunity')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpShoppingTrolley: typeof import('~icons/ep/shopping-trolley')['default']
    IEpStar: typeof import('~icons/ep/star')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
